"""initial baseline

Revision ID: 22348998243b
Revises: 
Create Date: 2026-05-04 02:34:19.059869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22348998243b'
down_revision: str = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_studio_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('niche', sa.String(length=240), nullable=False),
    sa.Column('target_viewer', sa.String(length=240), nullable=False),
    sa.Column('content_pillars_json', sa.Text(), nullable=False),
    sa.Column('title_style', sa.Text(), nullable=False),
    sa.Column('thumbnail_style', sa.Text(), nullable=False),
    sa.Column('script_style', sa.Text(), nullable=False),
    sa.Column('compliance_notes', sa.Text(), nullable=False),
    sa.Column('launch_wave', sa.Integer(), nullable=False),
    sa.Column('launch_status', sa.String(length=40), nullable=False),
    sa.Column('channel_url', sa.Text(), nullable=True),
    sa.Column('channel_handle', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_studio_agents_id'), 'channel_studio_agents', ['id'], unique=False)
    op.create_index(op.f('ix_channel_studio_agents_launch_status'), 'channel_studio_agents', ['launch_status'], unique=False)
    op.create_index(op.f('ix_channel_studio_agents_launch_wave'), 'channel_studio_agents', ['launch_wave'], unique=False)
    op.create_index(op.f('ix_channel_studio_agents_name'), 'channel_studio_agents', ['name'], unique=True)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('niche', sa.String(length=240), nullable=False),
    sa.Column('audience', sa.String(length=500), nullable=False),
    sa.Column('brand_voice', sa.String(length=500), nullable=False),
    sa.Column('visual_style', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_index(op.f('ix_channels_name'), 'channels', ['name'], unique=True)
    op.create_table('content_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('lane', sa.String(length=240), nullable=False),
    sa.Column('focus', sa.Text(), nullable=False),
    sa.Column('monetization_focus', sa.Text(), nullable=False),
    sa.Column('compliance_notes', sa.Text(), nullable=False),
    sa.Column('production_rules', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_agents_channel_id'), 'content_agents', ['channel_id'], unique=False)
    op.create_index(op.f('ix_content_agents_id'), 'content_agents', ['id'], unique=False)
    op.create_index(op.f('ix_content_agents_is_active'), 'content_agents', ['is_active'], unique=False)
    op.create_index(op.f('ix_content_agents_name'), 'content_agents', ['name'], unique=False)
    op.create_table('research_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('assigned_agent_id', sa.Integer(), nullable=True),
    sa.Column('niche_lane', sa.String(length=240), nullable=False),
    sa.Column('query', sa.String(length=240), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('setup_required', sa.Boolean(), nullable=False),
    sa.Column('setup_message', sa.Text(), nullable=True),
    sa.Column('source_video_count', sa.Integer(), nullable=False),
    sa.Column('source_channel_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['content_agents.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_assigned_agent_id'), 'research_runs', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_research_runs_channel_id'), 'research_runs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_research_runs_id'), 'research_runs', ['id'], unique=False)
    op.create_index(op.f('ix_research_runs_status'), 'research_runs', ['status'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('assigned_agent_id', sa.Integer(), nullable=True),
    sa.Column('channel_studio_agent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('content_type', sa.Enum('long', 'short', name='contenttype'), nullable=False),
    sa.Column('pillar', sa.String(length=120), nullable=False),
    sa.Column('target_viewer', sa.String(length=240), nullable=False),
    sa.Column('pain_point', sa.String(length=500), nullable=False),
    sa.Column('demo_idea', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_text', sa.String(length=80), nullable=False),
    sa.Column('niche', sa.String(length=240), nullable=True),
    sa.Column('target_audience', sa.String(length=500), nullable=True),
    sa.Column('angle', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('idea', 'drafted', 'needs_review', 'approved', 'packaged', 'publish_ready', 'published', 'rejected', name='videostatus'), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('publish_status', sa.String(length=60), nullable=False),
    sa.Column('publish_notes', sa.Text(), nullable=True),
    sa.Column('rendered_preview_path', sa.Text(), nullable=True),
    sa.Column('preview_rendered_at', sa.DateTime(), nullable=True),
    sa.Column('preview_reviewed', sa.Boolean(), nullable=False),
    sa.Column('preview_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('final_review_packet_path', sa.Text(), nullable=True),
    sa.Column('final_approval_status', sa.String(length=40), nullable=False),
    sa.Column('final_approval_notes', sa.Text(), nullable=True),
    sa.Column('final_approval_decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['content_agents.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['channel_studio_agent_id'], ['channel_studio_agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_assigned_agent_id'), 'videos', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_videos_channel_id'), 'videos', ['channel_id'], unique=False)
    op.create_index(op.f('ix_videos_channel_studio_agent_id'), 'videos', ['channel_studio_agent_id'], unique=False)
    op.create_index(op.f('ix_videos_final_approval_status'), 'videos', ['final_approval_status'], unique=False)
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.create_index(op.f('ix_videos_status'), 'videos', ['status'], unique=False)
    op.create_index(op.f('ix_videos_title'), 'videos', ['title'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_audit_events_video_id'), 'audit_events', ['video_id'], unique=False)
    op.create_table('content_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.Enum('brief', 'script', 'shorts', 'description', 'thumbnail_prompt', 'youtube_metadata', 'package_manifest', name='assettype'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_assets_asset_type'), 'content_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_content_assets_id'), 'content_assets', ['id'], unique=False)
    op.create_index(op.f('ix_content_assets_video_id'), 'content_assets', ['video_id'], unique=False)
    op.create_table('publish_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=60), nullable=False),
    sa.Column('external_id', sa.String(length=240), nullable=True),
    sa.Column('metadata_body', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_records_id'), 'publish_records', ['id'], unique=False)
    op.create_index(op.f('ix_publish_records_video_id'), 'publish_records', ['video_id'], unique=False)
    op.create_table('publishing_payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('payload_path', sa.Text(), nullable=False),
    sa.Column('payload_status', sa.String(length=40), nullable=False),
    sa.Column('ready_for_manual_upload', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('category_id', sa.String(length=40), nullable=False),
    sa.Column('privacy_status', sa.String(length=40), nullable=False),
    sa.Column('made_for_kids', sa.Boolean(), nullable=False),
    sa.Column('video_file_path', sa.Text(), nullable=True),
    sa.Column('thumbnail_image_path', sa.Text(), nullable=True),
    sa.Column('export_path', sa.Text(), nullable=True),
    sa.Column('blockers_json', sa.Text(), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=False),
    sa.Column('manual_upload_checklist_json', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_payloads_generated_at'), 'publishing_payloads', ['generated_at'], unique=False)
    op.create_index(op.f('ix_publishing_payloads_id'), 'publishing_payloads', ['id'], unique=False)
    op.create_index(op.f('ix_publishing_payloads_payload_status'), 'publishing_payloads', ['payload_status'], unique=False)
    op.create_index(op.f('ix_publishing_payloads_ready_for_manual_upload'), 'publishing_payloads', ['ready_for_manual_upload'], unique=False)
    op.create_index(op.f('ix_publishing_payloads_video_id'), 'publishing_payloads', ['video_id'], unique=True)
    op.create_table('research_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('pattern_type', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=240), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('signal_strength', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_patterns_id'), 'research_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_research_patterns_pattern_type'), 'research_patterns', ['pattern_type'], unique=False)
    op.create_index(op.f('ix_research_patterns_run_id'), 'research_patterns', ['run_id'], unique=False)
    op.create_table('research_source_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description_snippet', sa.Text(), nullable=False),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_source_channels_id'), 'research_source_channels', ['id'], unique=False)
    op.create_index(op.f('ix_research_source_channels_run_id'), 'research_source_channels', ['run_id'], unique=False)
    op.create_index(op.f('ix_research_source_channels_youtube_channel_id'), 'research_source_channels', ['youtube_channel_id'], unique=False)
    op.create_table('research_source_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=60), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('channel_title', sa.String(length=240), nullable=False),
    sa.Column('description_snippet', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=40), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_source_videos_id'), 'research_source_videos', ['id'], unique=False)
    op.create_index(op.f('ix_research_source_videos_run_id'), 'research_source_videos', ['run_id'], unique=False)
    op.create_index(op.f('ix_research_source_videos_youtube_channel_id'), 'research_source_videos', ['youtube_channel_id'], unique=False)
    op.create_index(op.f('ix_research_source_videos_youtube_video_id'), 'research_source_videos', ['youtube_video_id'], unique=False)
    op.create_table('research_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('assigned_agent_id', sa.Integer(), nullable=True),
    sa.Column('recommended_agent_name', sa.String(length=160), nullable=True),
    sa.Column('niche_lane', sa.String(length=240), nullable=False),
    sa.Column('query', sa.String(length=240), nullable=False),
    sa.Column('trend_thesis', sa.Text(), nullable=False),
    sa.Column('winning_patterns', sa.Text(), nullable=False),
    sa.Column('original_video_angles', sa.Text(), nullable=False),
    sa.Column('recommended_topics_json', sa.Text(), nullable=False),
    sa.Column('title_directions', sa.Text(), nullable=False),
    sa.Column('thumbnail_directions', sa.Text(), nullable=False),
    sa.Column('hook_directions', sa.Text(), nullable=False),
    sa.Column('monetization_path', sa.Text(), nullable=False),
    sa.Column('differentiation_strategy', sa.Text(), nullable=False),
    sa.Column('what_not_to_copy', sa.Text(), nullable=False),
    sa.Column('compliance_risks', sa.Text(), nullable=False),
    sa.Column('recommended_next_action', sa.Text(), nullable=False),
    sa.Column('top_pattern', sa.String(length=240), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['content_agents.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_strategies_assigned_agent_id'), 'research_strategies', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_research_strategies_id'), 'research_strategies', ['id'], unique=False)
    op.create_index(op.f('ix_research_strategies_run_id'), 'research_strategies', ['run_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('reviewer', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_video_id'), 'reviews', ['video_id'], unique=False)
    op.create_table('video_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('assigned_agent_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=240), nullable=False),
    sa.Column('niche_lane', sa.String(length=240), nullable=False),
    sa.Column('audience', sa.String(length=500), nullable=False),
    sa.Column('monetization_path', sa.String(length=240), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('search_demand', sa.Integer(), nullable=False),
    sa.Column('buyer_intent', sa.Integer(), nullable=False),
    sa.Column('affiliate_potential', sa.Integer(), nullable=False),
    sa.Column('sponsorship_potential', sa.Integer(), nullable=False),
    sa.Column('production_difficulty', sa.Integer(), nullable=False),
    sa.Column('compliance_risk', sa.Integer(), nullable=False),
    sa.Column('trend_freshness', sa.Integer(), nullable=False),
    sa.Column('product_connection', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('expected_monetization_path', sa.String(length=240), nullable=False),
    sa.Column('why_make_this', sa.Text(), nullable=False),
    sa.Column('recommended_title', sa.String(length=240), nullable=False),
    sa.Column('thumbnail_angle', sa.String(length=240), nullable=False),
    sa.Column('recommended_cta', sa.String(length=240), nullable=False),
    sa.Column('assigned_agent', sa.String(length=120), nullable=False),
    sa.Column('compliance_risk_note', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=40), nullable=False),
    sa.Column('operator_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('decision_summary', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('promoted_video_id', sa.Integer(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['content_agents.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['promoted_video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_opportunities_assigned_agent_id'), 'video_opportunities', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_video_opportunities_channel_id'), 'video_opportunities', ['channel_id'], unique=False)
    op.create_index(op.f('ix_video_opportunities_id'), 'video_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_video_opportunities_review_status'), 'video_opportunities', ['review_status'], unique=False)
    op.create_index(op.f('ix_video_opportunities_topic'), 'video_opportunities', ['topic'], unique=False)
    op.create_index(op.f('ix_video_opportunities_total_score'), 'video_opportunities', ['total_score'], unique=False)
    op.create_table('video_performance_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=60), nullable=False),
    sa.Column('published_url', sa.Text(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('average_view_duration_seconds', sa.Float(), nullable=True),
    sa.Column('average_percentage_viewed', sa.Float(), nullable=True),
    sa.Column('watch_time_minutes', sa.Float(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('subscribers_gained', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_performance_metrics_id'), 'video_performance_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_video_performance_metrics_measured_at'), 'video_performance_metrics', ['measured_at'], unique=False)
    op.create_index(op.f('ix_video_performance_metrics_platform'), 'video_performance_metrics', ['platform'], unique=False)
    op.create_index(op.f('ix_video_performance_metrics_video_id'), 'video_performance_metrics', ['video_id'], unique=False)
    op.create_table('executive_producer_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selected_opportunity_id', sa.Integer(), nullable=True),
    sa.Column('matched_agent_id', sa.Integer(), nullable=True),
    sa.Column('matched_agent_name', sa.String(length=160), nullable=True),
    sa.Column('matched_agent_lane', sa.String(length=240), nullable=True),
    sa.Column('selected_review_status', sa.String(length=40), nullable=True),
    sa.Column('recommended_topic', sa.String(length=240), nullable=True),
    sa.Column('niche_lane', sa.String(length=240), nullable=True),
    sa.Column('assigned_agent', sa.String(length=120), nullable=True),
    sa.Column('recommended_title', sa.String(length=240), nullable=True),
    sa.Column('thumbnail_angle', sa.String(length=240), nullable=True),
    sa.Column('recommended_cta', sa.String(length=240), nullable=True),
    sa.Column('monetization_path', sa.String(length=240), nullable=True),
    sa.Column('why_make_today', sa.Text(), nullable=True),
    sa.Column('risks_to_review', sa.Text(), nullable=True),
    sa.Column('operator_checklist', sa.Text(), nullable=True),
    sa.Column('production_brief', sa.Text(), nullable=True),
    sa.Column('confidence_label', sa.String(length=20), nullable=False),
    sa.Column('selection_score', sa.Integer(), nullable=True),
    sa.Column('empty_state_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matched_agent_id'], ['content_agents.id'], ),
    sa.ForeignKeyConstraint(['selected_opportunity_id'], ['video_opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executive_producer_recommendations_id'), 'executive_producer_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_executive_producer_recommendations_matched_agent_id'), 'executive_producer_recommendations', ['matched_agent_id'], unique=False)
    op.create_index(op.f('ix_executive_producer_recommendations_selected_opportunity_id'), 'executive_producer_recommendations', ['selected_opportunity_id'], unique=False)
    op.create_table('production_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('assigned_agent_id', sa.Integer(), nullable=True),
    sa.Column('promoted_video_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('topic', sa.String(length=240), nullable=False),
    sa.Column('niche_lane', sa.String(length=240), nullable=False),
    sa.Column('target_audience', sa.String(length=500), nullable=False),
    sa.Column('monetization_path', sa.String(length=240), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('thumbnail_angle', sa.String(length=240), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('outline', sa.Text(), nullable=False),
    sa.Column('script_plan', sa.Text(), nullable=False),
    sa.Column('b_roll_plan', sa.Text(), nullable=False),
    sa.Column('voiceover_style', sa.Text(), nullable=False),
    sa.Column('cta', sa.String(length=240), nullable=False),
    sa.Column('compliance_notes', sa.Text(), nullable=False),
    sa.Column('claims_to_verify', sa.Text(), nullable=False),
    sa.Column('operator_review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['content_agents.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['video_opportunities.id'], ),
    sa.ForeignKeyConstraint(['promoted_video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_briefs_assigned_agent_id'), 'production_briefs', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_production_briefs_id'), 'production_briefs', ['id'], unique=False)
    op.create_index(op.f('ix_production_briefs_opportunity_id'), 'production_briefs', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_production_briefs_promoted_video_id'), 'production_briefs', ['promoted_video_id'], unique=False)
    op.create_index(op.f('ix_production_briefs_status'), 'production_briefs', ['status'], unique=False)
    op.create_table('autopilot_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('brief_id', sa.Integer(), nullable=True),
    sa.Column('run_status', sa.String(length=40), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('ready_for_final_approval_count', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=False),
    sa.Column('blockers_json', sa.Text(), nullable=False),
    sa.Column('videos_json', sa.Text(), nullable=False),
    sa.Column('final_review_packet_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['channel_studio_agents.id'], ),
    sa.ForeignKeyConstraint(['brief_id'], ['production_briefs.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['video_opportunities.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autopilot_runs_agent_id'), 'autopilot_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_autopilot_runs_brief_id'), 'autopilot_runs', ['brief_id'], unique=False)
    op.create_index(op.f('ix_autopilot_runs_content_type'), 'autopilot_runs', ['content_type'], unique=False)
    op.create_index(op.f('ix_autopilot_runs_id'), 'autopilot_runs', ['id'], unique=False)
    op.create_index(op.f('ix_autopilot_runs_opportunity_id'), 'autopilot_runs', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_autopilot_runs_run_status'), 'autopilot_runs', ['run_status'], unique=False)
    op.create_index(op.f('ix_autopilot_runs_video_id'), 'autopilot_runs', ['video_id'], unique=False)
    op.create_table('visual_asset_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('brief_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('thumbnail_prompt', sa.Text(), nullable=False),
    sa.Column('thumbnail_text', sa.String(length=120), nullable=False),
    sa.Column('motion_style', sa.String(length=240), nullable=False),
    sa.Column('color_direction', sa.String(length=240), nullable=False),
    sa.Column('plan_notes', sa.Text(), nullable=True),
    sa.Column('safety_notes', sa.Text(), nullable=False),
    sa.Column('ready_marked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['production_briefs.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_asset_plans_brief_id'), 'visual_asset_plans', ['brief_id'], unique=False)
    op.create_index(op.f('ix_visual_asset_plans_id'), 'visual_asset_plans', ['id'], unique=False)
    op.create_index(op.f('ix_visual_asset_plans_source_type'), 'visual_asset_plans', ['source_type'], unique=False)
    op.create_index(op.f('ix_visual_asset_plans_status'), 'visual_asset_plans', ['status'], unique=False)
    op.create_index(op.f('ix_visual_asset_plans_video_id'), 'visual_asset_plans', ['video_id'], unique=False)
    op.create_table('visual_scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('scene_title', sa.String(length=200), nullable=False),
    sa.Column('narrative_beat', sa.Text(), nullable=False),
    sa.Column('on_screen_text', sa.String(length=180), nullable=False),
    sa.Column('image_prompt', sa.Text(), nullable=False),
    sa.Column('animation_prompt', sa.Text(), nullable=False),
    sa.Column('b_roll_prompt', sa.Text(), nullable=False),
    sa.Column('dashboard_demo_prompt', sa.Text(), nullable=False),
    sa.Column('safety_notes', sa.Text(), nullable=False),
    sa.Column('asset_status', sa.String(length=40), nullable=False),
    sa.Column('generated_asset_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['visual_asset_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_scenes_asset_status'), 'visual_scenes', ['asset_status'], unique=False)
    op.create_index(op.f('ix_visual_scenes_id'), 'visual_scenes', ['id'], unique=False)
    op.create_index(op.f('ix_visual_scenes_plan_id'), 'visual_scenes', ['plan_id'], unique=False)
    op.create_index(op.f('ix_visual_scenes_scene_number'), 'visual_scenes', ['scene_number'], unique=False)
    op.create_table('visual_asset_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('prompt_type', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['visual_asset_plans.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['visual_scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_asset_prompts_id'), 'visual_asset_prompts', ['id'], unique=False)
    op.create_index(op.f('ix_visual_asset_prompts_plan_id'), 'visual_asset_prompts', ['plan_id'], unique=False)
    op.create_index(op.f('ix_visual_asset_prompts_prompt_type'), 'visual_asset_prompts', ['prompt_type'], unique=False)
    op.create_index(op.f('ix_visual_asset_prompts_scene_id'), 'visual_asset_prompts', ['scene_id'], unique=False)
    op.create_table('visual_generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visual_asset_plan_id', sa.Integer(), nullable=False),
    sa.Column('visual_scene_id', sa.Integer(), nullable=True),
    sa.Column('prompt_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('provider_payload_json', sa.Text(), nullable=False),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['visual_asset_prompts.id'], ),
    sa.ForeignKeyConstraint(['visual_asset_plan_id'], ['visual_asset_plans.id'], ),
    sa.ForeignKeyConstraint(['visual_scene_id'], ['visual_scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_generation_jobs_id'), 'visual_generation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_visual_generation_jobs_job_type'), 'visual_generation_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_visual_generation_jobs_prompt_id'), 'visual_generation_jobs', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_visual_generation_jobs_provider'), 'visual_generation_jobs', ['provider'], unique=False)
    op.create_index(op.f('ix_visual_generation_jobs_status'), 'visual_generation_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_visual_generation_jobs_visual_asset_plan_id'), 'visual_generation_jobs', ['visual_asset_plan_id'], unique=False)
    op.create_index(op.f('ix_visual_generation_jobs_visual_scene_id'), 'visual_generation_jobs', ['visual_scene_id'], unique=False)
    op.create_table('visual_generated_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visual_asset_plan_id', sa.Integer(), nullable=False),
    sa.Column('visual_scene_id', sa.Integer(), nullable=True),
    sa.Column('generation_job_id', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(length=40), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_exists', sa.Boolean(), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generation_job_id'], ['visual_generation_jobs.id'], ),
    sa.ForeignKeyConstraint(['visual_asset_plan_id'], ['visual_asset_plans.id'], ),
    sa.ForeignKeyConstraint(['visual_scene_id'], ['visual_scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_generated_assets_asset_type'), 'visual_generated_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_visual_generated_assets_file_exists'), 'visual_generated_assets', ['file_exists'], unique=False)
    op.create_index(op.f('ix_visual_generated_assets_generation_job_id'), 'visual_generated_assets', ['generation_job_id'], unique=False)
    op.create_index(op.f('ix_visual_generated_assets_id'), 'visual_generated_assets', ['id'], unique=False)
    op.create_index(op.f('ix_visual_generated_assets_visual_asset_plan_id'), 'visual_generated_assets', ['visual_asset_plan_id'], unique=False)
    op.create_index(op.f('ix_visual_generated_assets_visual_scene_id'), 'visual_generated_assets', ['visual_scene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visual_generated_assets_visual_scene_id'), table_name='visual_generated_assets')
    op.drop_index(op.f('ix_visual_generated_assets_visual_asset_plan_id'), table_name='visual_generated_assets')
    op.drop_index(op.f('ix_visual_generated_assets_id'), table_name='visual_generated_assets')
    op.drop_index(op.f('ix_visual_generated_assets_generation_job_id'), table_name='visual_generated_assets')
    op.drop_index(op.f('ix_visual_generated_assets_file_exists'), table_name='visual_generated_assets')
    op.drop_index(op.f('ix_visual_generated_assets_asset_type'), table_name='visual_generated_assets')
    op.drop_table('visual_generated_assets')
    op.drop_index(op.f('ix_visual_generation_jobs_visual_scene_id'), table_name='visual_generation_jobs')
    op.drop_index(op.f('ix_visual_generation_jobs_visual_asset_plan_id'), table_name='visual_generation_jobs')
    op.drop_index(op.f('ix_visual_generation_jobs_status'), table_name='visual_generation_jobs')
    op.drop_index(op.f('ix_visual_generation_jobs_provider'), table_name='visual_generation_jobs')
    op.drop_index(op.f('ix_visual_generation_jobs_prompt_id'), table_name='visual_generation_jobs')
    op.drop_index(op.f('ix_visual_generation_jobs_job_type'), table_name='visual_generation_jobs')
    op.drop_index(op.f('ix_visual_generation_jobs_id'), table_name='visual_generation_jobs')
    op.drop_table('visual_generation_jobs')
    op.drop_index(op.f('ix_visual_asset_prompts_scene_id'), table_name='visual_asset_prompts')
    op.drop_index(op.f('ix_visual_asset_prompts_prompt_type'), table_name='visual_asset_prompts')
    op.drop_index(op.f('ix_visual_asset_prompts_plan_id'), table_name='visual_asset_prompts')
    op.drop_index(op.f('ix_visual_asset_prompts_id'), table_name='visual_asset_prompts')
    op.drop_table('visual_asset_prompts')
    op.drop_index(op.f('ix_visual_scenes_scene_number'), table_name='visual_scenes')
    op.drop_index(op.f('ix_visual_scenes_plan_id'), table_name='visual_scenes')
    op.drop_index(op.f('ix_visual_scenes_id'), table_name='visual_scenes')
    op.drop_index(op.f('ix_visual_scenes_asset_status'), table_name='visual_scenes')
    op.drop_table('visual_scenes')
    op.drop_index(op.f('ix_visual_asset_plans_video_id'), table_name='visual_asset_plans')
    op.drop_index(op.f('ix_visual_asset_plans_status'), table_name='visual_asset_plans')
    op.drop_index(op.f('ix_visual_asset_plans_source_type'), table_name='visual_asset_plans')
    op.drop_index(op.f('ix_visual_asset_plans_id'), table_name='visual_asset_plans')
    op.drop_index(op.f('ix_visual_asset_plans_brief_id'), table_name='visual_asset_plans')
    op.drop_table('visual_asset_plans')
    op.drop_index(op.f('ix_autopilot_runs_video_id'), table_name='autopilot_runs')
    op.drop_index(op.f('ix_autopilot_runs_run_status'), table_name='autopilot_runs')
    op.drop_index(op.f('ix_autopilot_runs_opportunity_id'), table_name='autopilot_runs')
    op.drop_index(op.f('ix_autopilot_runs_id'), table_name='autopilot_runs')
    op.drop_index(op.f('ix_autopilot_runs_content_type'), table_name='autopilot_runs')
    op.drop_index(op.f('ix_autopilot_runs_brief_id'), table_name='autopilot_runs')
    op.drop_index(op.f('ix_autopilot_runs_agent_id'), table_name='autopilot_runs')
    op.drop_table('autopilot_runs')
    op.drop_index(op.f('ix_production_briefs_status'), table_name='production_briefs')
    op.drop_index(op.f('ix_production_briefs_promoted_video_id'), table_name='production_briefs')
    op.drop_index(op.f('ix_production_briefs_opportunity_id'), table_name='production_briefs')
    op.drop_index(op.f('ix_production_briefs_id'), table_name='production_briefs')
    op.drop_index(op.f('ix_production_briefs_assigned_agent_id'), table_name='production_briefs')
    op.drop_table('production_briefs')
    op.drop_index(op.f('ix_executive_producer_recommendations_selected_opportunity_id'), table_name='executive_producer_recommendations')
    op.drop_index(op.f('ix_executive_producer_recommendations_matched_agent_id'), table_name='executive_producer_recommendations')
    op.drop_index(op.f('ix_executive_producer_recommendations_id'), table_name='executive_producer_recommendations')
    op.drop_table('executive_producer_recommendations')
    op.drop_index(op.f('ix_video_performance_metrics_video_id'), table_name='video_performance_metrics')
    op.drop_index(op.f('ix_video_performance_metrics_platform'), table_name='video_performance_metrics')
    op.drop_index(op.f('ix_video_performance_metrics_measured_at'), table_name='video_performance_metrics')
    op.drop_index(op.f('ix_video_performance_metrics_id'), table_name='video_performance_metrics')
    op.drop_table('video_performance_metrics')
    op.drop_index(op.f('ix_video_opportunities_total_score'), table_name='video_opportunities')
    op.drop_index(op.f('ix_video_opportunities_topic'), table_name='video_opportunities')
    op.drop_index(op.f('ix_video_opportunities_review_status'), table_name='video_opportunities')
    op.drop_index(op.f('ix_video_opportunities_id'), table_name='video_opportunities')
    op.drop_index(op.f('ix_video_opportunities_channel_id'), table_name='video_opportunities')
    op.drop_index(op.f('ix_video_opportunities_assigned_agent_id'), table_name='video_opportunities')
    op.drop_table('video_opportunities')
    op.drop_index(op.f('ix_reviews_video_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_research_strategies_run_id'), table_name='research_strategies')
    op.drop_index(op.f('ix_research_strategies_id'), table_name='research_strategies')
    op.drop_index(op.f('ix_research_strategies_assigned_agent_id'), table_name='research_strategies')
    op.drop_table('research_strategies')
    op.drop_index(op.f('ix_research_source_videos_youtube_video_id'), table_name='research_source_videos')
    op.drop_index(op.f('ix_research_source_videos_youtube_channel_id'), table_name='research_source_videos')
    op.drop_index(op.f('ix_research_source_videos_run_id'), table_name='research_source_videos')
    op.drop_index(op.f('ix_research_source_videos_id'), table_name='research_source_videos')
    op.drop_table('research_source_videos')
    op.drop_index(op.f('ix_research_source_channels_youtube_channel_id'), table_name='research_source_channels')
    op.drop_index(op.f('ix_research_source_channels_run_id'), table_name='research_source_channels')
    op.drop_index(op.f('ix_research_source_channels_id'), table_name='research_source_channels')
    op.drop_table('research_source_channels')
    op.drop_index(op.f('ix_research_patterns_run_id'), table_name='research_patterns')
    op.drop_index(op.f('ix_research_patterns_pattern_type'), table_name='research_patterns')
    op.drop_index(op.f('ix_research_patterns_id'), table_name='research_patterns')
    op.drop_table('research_patterns')
    op.drop_index(op.f('ix_publishing_payloads_video_id'), table_name='publishing_payloads')
    op.drop_index(op.f('ix_publishing_payloads_ready_for_manual_upload'), table_name='publishing_payloads')
    op.drop_index(op.f('ix_publishing_payloads_payload_status'), table_name='publishing_payloads')
    op.drop_index(op.f('ix_publishing_payloads_id'), table_name='publishing_payloads')
    op.drop_index(op.f('ix_publishing_payloads_generated_at'), table_name='publishing_payloads')
    op.drop_table('publishing_payloads')
    op.drop_index(op.f('ix_publish_records_video_id'), table_name='publish_records')
    op.drop_index(op.f('ix_publish_records_id'), table_name='publish_records')
    op.drop_table('publish_records')
    op.drop_index(op.f('ix_content_assets_video_id'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_id'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_asset_type'), table_name='content_assets')
    op.drop_table('content_assets')
    op.drop_index(op.f('ix_audit_events_video_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_videos_title'), table_name='videos')
    op.drop_index(op.f('ix_videos_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_final_approval_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_channel_studio_agent_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_channel_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_assigned_agent_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_research_runs_status'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_channel_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_assigned_agent_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index(op.f('ix_content_agents_name'), table_name='content_agents')
    op.drop_index(op.f('ix_content_agents_is_active'), table_name='content_agents')
    op.drop_index(op.f('ix_content_agents_id'), table_name='content_agents')
    op.drop_index(op.f('ix_content_agents_channel_id'), table_name='content_agents')
    op.drop_table('content_agents')
    op.drop_index(op.f('ix_channels_name'), table_name='channels')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_channel_studio_agents_name'), table_name='channel_studio_agents')
    op.drop_index(op.f('ix_channel_studio_agents_launch_wave'), table_name='channel_studio_agents')
    op.drop_index(op.f('ix_channel_studio_agents_launch_status'), table_name='channel_studio_agents')
    op.drop_index(op.f('ix_channel_studio_agents_id'), table_name='channel_studio_agents')
    op.drop_table('channel_studio_agents')
    # ### end Alembic commands ###